version: '3.9'

services:

  bot:
    build: .
    container_name: music_bot

    env_file:
      - .env

    depends_on:
      - redis
      - postgres

  redis:
    image: redis

  postgres:
    image: postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 55055904855
      POSTGRES_DB: music_bot

    ports:
      - "5432:5432"